### ISSUE TITLE
Frage 126. Wie lange vor deinem Seminarabgabetermin warst du fertig?

### ISSUE THREAD

**Issue by dieechtenilente** [okitec/abivote#7]
Wieviele Arten gibt es, "Vortag" anzugeben. Richtig. Nicht so viele.

**Comment by okitec** [comment]
Pffffft

**Comment by dieechtenilente** [comment]
Ey D:

**Comment by okitec** [comment]
Sorry, aber das Issue-schließen war einfach zu funny, ums nicht zu machen  :P
Wollte trotzdem keine Radiofrage draus machen, auch wenns evtl. sinnvoll gewesen wäre. Ursprünglich war es sogar eine, aber ...

Vielleicht will ich ja herausfinden, wie man "Vortag" so ausdrücken kann.

**Comment by dieechtenilente** [comment]
Okay :D
